matrix:
  include:
#    - env: SUBSURFACE_PLATFORM='mac'
#      os: osx
#      osx_image: xcode6.4
#      language: c++ ruby
#
#    - env: SUBSURFACE_PLATFORM='windows'
#      os: linux
#      dist: trusty
#      sudo: required
#      language: c++

    - env: SUBSURFACE_PLATFORM='linux'
      os: linux
      dist: trusty
      sudo: required
      language: c++
      addons:
        apt:
          packages:
            - git
            - g++
            - make
            - autoconf
            - automake
            - libtool
            - cmake
            - pkg-config
            - libxml2-dev
            - libxslt1-dev
            - libzip-dev
            - libsqlite3-dev
            - libusb-1.0-0-dev
            - libssl-dev
            - libssh2-1-dev
            - libcurl4-openssl-dev
            # Not a subsurface dependency, but a Qt dependency
            - mesa-common-dev
            - libqt5gui5
            - libxcb-xinerama0
            # Not a subsurface dependency, but a QtMultimedia/libdeclarative_multimedia.so dependency
            - libpulse-mainloop-glib0
            # Not a subsurface dependency, but a QtWebKit dependency
            - libhyphen-dev
            - libicu52
        coverity_scan:
          project:
            name: "Subsurface-divelog/subsurface"
            description: "Build submitted via Travis CI"
          notification_email: glance@acc.umu.se
          build_command: bash ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/travisbuild.sh
          branch_pattern: coverity_scan

#    - env: SUBSURFACE_PLATFORM="android"
#      # Currently hard coded to arm
#      os: linux
#      language: c++
#      filter_secrets: false
#      services:
#          - docker
# TODO: caching
#      cache:
#          timeout: 300
#          directories:
#              - 3pp

before_install:
    # When the build on this branch gets triggered by travis-cron, do a coverty scan.
    - if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ; then export COVERITY_SCAN_BRANCH=1 ; fi
    - source ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/before_install.sh

script:
    - if [ "$COVERITY_SCAN_BRANCH" != "1" ] ; then source ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/travisbuild.sh ; fi

after_success:
    - source ${TRAVIS_BUILD_DIR}/scripts/${SUBSURFACE_PLATFORM}/after_success.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
